on:
  workflow_dispatch:
    inputs:
      deploy_target:
        required: false
        type: string
      perform_deploy:
        required: true
        type: boolean

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Check if username is provided
        run: |
          if [[ inputs.perform_deploy == "true" ]]; then
            echo "The username is provided and is not '123'."
            USERNAME_PROVIDED=true
          else
            echo "The username is 'john-doe'."
            USERNAME_PROVIDED=false
          fi
