name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      is_secondary_region_up:
        default: 'false'
        required: true
        type: boolean

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking Variable Usage"
        run: | 
          if [[ "${{ github.event.inputs.is_secondary_region_up }}" == "true" ]]; then
            echo "Need=Yes" >> $GITHUB_ENV
          else
            echo "Need=No" >> $GITHUB_ENV
          fi
          
      - name: "Use the variable"
        run: echo "the output is ---> ${{ env.Need }}"
