on:
  workflow_dispatch:
    inputs:
      is_secondary_region_up:
        default: 'false'
        required: true
        type: boolean

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Check if username is provided
        run: |
          if ${{ github.event.inputs.is_secondary_region_up }}; then
            echo "Yes the seconadry region is up."
          fi
