name: Deploy to Prod us-east-2

# Summary
# Manually build and deploy prod environment

on:
  workflow_dispatch:
    inputs:
      is_secondary_region_active:
        default: 'false'
        required: true
        type: boolean
        
env:
  secondary_region: us-east-2

jobs:

  build:
    runs-on: Ubuntu-Latest
    steps:
      - name: "build"
        run: |
          echo "build"
    
  approval-for-deployment:
    needs: [build]
    runs-on: Ubuntu-Latest
    environment: prod-next
    steps:
      - name: "Workflow approved for deployment"
        run: |
          echo  "deployment pipeline approved"

  create-change-request:
    needs: [approval-for-deployment]
    runs-on: Ubuntu-Latest
    steps:
      - name: "create-change-request"
        run: |
          echo "create-change-request"


  deploy-to-prod:
    needs: [create-change-request]
    runs-on: Ubuntu-Latest
    steps:
      - name: "deploy-to-prod"
        run: |
          echo "deploy-to-prod"
 
  integration-testing:
    if: ${{ github.event.inputs.is_secondary_region_active == 'True'}}
    needs: [deploy-to-prod]
    runs-on: Ubuntu-Latest
    steps:
      - name: "integration-testing"
        run: |
          echo "integration-testing"
    

  promote-to-prod-when-secondary-region-active:
    if: ${{ github.event.inputs.is_secondary_region_active == 'True'}}
    needs: [integration-testing]
    runs-on: Ubuntu-Latest
    steps:
      - name: "promote-to-prod-when-secondary-region-active"
        run: |
          echo "promote-to-prod-when-secondary-region-active"
     

  promote-to-prod-when-secondary-region-not-active:
    if: ${{ github.event.inputs.is_secondary_region_active == 'false'}}
    needs: [deploy-to-prod]
    runs-on: Ubuntu-Latest
    steps:
      - name: "promote-to-prod-when-secondary-region-not-active"
        run: |
          echo "promote-to-prod-when-secondary-region-not-active"
          
  scale-down-prev-instance:
    if: ${{ github.event.inputs.is_secondary_region_active == 'True'}}
    needs: [promote-to-prod-when-secondary-region-active]
    runs-on: Ubuntu-Latest
    steps:
      - name: "scale-down-prev-instance"
        run: |
          echo "scale-down-prev-instance"
      
  close-change-request-failure-when-secondary-region-active:
    if: ${{ github.event.inputs.is_secondary_region_active == 'True'}}
    needs: [deploy-to-prod, promote-to-prod-when-secondary-region-active, scale-down-prev-instance, create-change-request]
    runs-on: Ubuntu-Latest
    steps:
      - name: "close-change-request-failure-when-secondary-region-active"
        run: |
          echo "close-change-request-failure-when-secondary-region-active"
    

  close-change-request-failure-when-secondary-region-not-active:
    if: ${{ github.event.inputs.is_secondary_region_active == 'false'}}
    needs: [deploy-to-prod, promote-to-prod-when-secondary-region-not-active, create-change-request]
    runs-on: Ubuntu-Latest
    steps:
      - name: "close-change-request-failure-when-secondary-region-not-active"
        run: |
          echo "close-change-request-failure-when-secondary-region-not-active"
    

  close-change-request-success-when-secondary-region-active:
    if: ${{ github.event.inputs.is_secondary_region_active == 'True'}}
    needs: [deploy-to-prod, promote-to-prod-when-secondary-region-active, scale-down-prev-instance, create-change-request]
    runs-on: Ubuntu-Latest
    steps:
      - name: "close-change-request-success-when-secondary-region-active"
        run: |
          echo "close-change-request-success-when-secondary-region-active"
    

  close-change-request-success_when_secondary_region_not_active:
    if: ${{ github.event.inputs.is_secondary_region_active == 'false'}}
    needs: [deploy-to-prod, promote-to-prod-when-secondary-region-not-active, create-change-request]
    runs-on: Ubuntu-Latest
    
    steps:
      - name: "close-change-request-success_when_secondary_region_not_active"
        run: |
          echo "close-change-request-success_when_secondary_region_not_active"
          env:
            AWS_SECRET_ACCESS_KEY: $secondary_region
          echo "$AWS_SECRET_ACCESS_KEY"
   
