name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      is_secondary_region_up:
        default: 'false'
        required: true
        type: boolean

env:
  DAY_OF_WEEK: Monday
  First_Name: Mona

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Checking Variable Usage"
        run: | 
          if [[ "${{ github.event.inputs.is_secondary_region_up }}" == "true" ]]; then
            echo "Secondary_region_is_active=Yes" >> $GITHUB_ENV
          else
            echo "Secondary_region_is_active=No" >> $GITHUB_ENV
          fi
          
      - name: "Use the variable"
        run: echo "$GITHUB_ENV"
