name: Deploy to Prod us-east-2

# Summary
# Manually build and deploy prod environment

on:
  workflow_dispatch:
    inputs:
      is_secondary_region_active:
        default: 'false'
        required: true
        type: boolean

env:
  Secondary_region: us-east-2

jobs:

  build:
    runs-on: Ubuntu-Latest
    steps:
      - name: "build"
        run: |
          echo "build"

  approval-for-deployment:
    needs: [build]
    runs-on: Ubuntu-Latest
    steps:
      - name: "Workflow approved for deployment"
        run: |
          echo "approval-for-deployment ."

  create-change-request:
    needs: [approval-for-deployment]
    runs-on: Ubuntu-Latest
    steps:
      - name: "Create change request"
        run: |
          echo "create-change-request ."

  deploy-to-prod:
    needs: [create-change-request]
    runs-on: Ubuntu-Latest
    steps:
      - name: "deploy-to-prod"
        run: |
          echo "deploy-to-prod ."

 
  integration-testing:
    runs-on: CAI-Enterprise-Ubuntu-Latest

    steps:
      - name: integration-testing
        run: |
          if ${{ github.event.inputs.is_secondary_region_active }}; then
            echo "integration-testing"
            echo "Need1=integration-testing" >> $GITHUB_ENV  
          else
            echo "integration-testing"
            echo "Need1=deploy-to-prod" >> $GITHUB_ENV 
          fi  

  promote-to-prod:
    needs: '${{ env.Need1 }}'
    runs-on: Ubuntu-Latest
    steps:
      - name: "promote-to-prod"
        run: |
          echo "promote-to-prod ."  

  scale-down-prev-instance:
    needs: [promote-to-prod]
    runs-on: Ubuntu-Latest
    steps:
      - name: scale-down-prev-instance
        run: |
          if ${{ github.event.inputs.is_secondary_region_active }}; then
            echo "scale-down-prev-instance ."
            echo "Need2=scale-down-prev-instance" >> $GITHUB_ENV  
          else
            echo "scale-down-prev-instance ."
            echo "Need2=promote-to-prod" >> $GITHUB_ENV 
          fi        

  close-change-request-failure:
    needs:  '${{ env.Need2 }}'
    runs-on: Ubuntu-Latest
    steps:
      - name: "close-change-request-failure"
        run: |
          echo "close-change-request-failure"
    

  close-change-request-success:
    needs: '${{ env.Need2 }}'
    runs-on: CAI-Enterprise-Ubuntu-Latest
    steps:
      - name: "close-change-request-success"
        run: |
          echo "close-change-request-success ."
    
