name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      is_secondary_region_up:
        default: 'false'
        required: true
        type: boolean

env:
  DAY_OF_WEEK: Monday
  First_Name: Mona

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: | 
          if ${{ github.event.inputs.is_secondary_region_up }}; then
            echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          else
            echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          fi  
       
