on:
  workflow_dispatch:
    inputs:
      is_secondary_region_up:
        description: 'Checking whether the ECS in Secondary Region ( us-east-2 ) is up or not'
        default: 'false'
        required: true
        type: boolean

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Check if username is provided
        run: |
          if ${{ inputs.perform_deploy }}; then
            echo "The username is provided and is not '123'."
            USERNAME_PROVIDED=true
          else
            echo "The username is 'john-doe'."
            USERNAME_PROVIDED=false
          fi
